ACCOUNT_PERSONAL = 'personal'
ACCOUNT_BUSINESS = 'business'

CURRENCY_RON = "RON"
CURRENCY_EUR = "EUR"
CURRENCY_USD = "USD"

STATEMENT_TYPE_ACCOUNTING = "FLAT"

ONE_TIME_TOKEN_HEADER = 'x-2fa-approval'
ONE_TIME_TOKEN_SIGNATURE_HEADER = 'X-Signature'